version: '2'
services:
  db:
    #build: postgres-gnuhealth
    image: mbsolutions/postgres-gnuhealth:3.0
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecret
    ports:
      - "5432:5432"

  tryton:
    #build: tryton-server-gnuhealth
    image: tryton-server-gnuhealth
    volumes:
      - ./tryton-data:/var/lib/tryton
    environment:
      - TRYTOND_PASSWORD=admin
    ports:
      - "2575:2575"
      - "5000:5000"
      - "8000:8000"
    links:
      - db
